//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epos.Lib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ExamID { get; set; }
        public int PatientID { get; set; }
        public string ExamText { get; set; }
        public System.DateTime ExamDate { get; set; }
        public Nullable<System.DateTime> ExamCorrectDate { get; set; }
        public Nullable<int> CorrectExamID { get; set; }
        public Nullable<int> SavedInd { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string UserName { get; set; }
    }
}
