//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epos.Lib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamDefault
    {
        public int ExamDefaultID { get; set; }
        public string DefaultName { get; set; }
        public int AgeStart { get; set; }
        public int AgeEnd { get; set; }
        public bool PrematureBirth { get; set; }
        public int DoctorUserID { get; set; }
        public string ExamText { get; set; }
    }
}
