//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epos.Lib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamLookUp
    {
        public int ExamLookUpID { get; set; }
        public string ControlName { get; set; }
        public string FieldName { get; set; }
        public string ExamChildDefault { get; set; }
        public string ExamInfantDefault { get; set; }
        public string ExamAdultDefault { get; set; }
        public string ExamROPDefault { get; set; }
        public string FieldDescription { get; set; }
    }
}
