//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epos.Lib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamDataConfiguration
    {
        public int ExamDataConfigurationID { get; set; }
        public string Name { get; set; }
        public int FieldDataType { get; set; }
        public string Field { get; set; }
    }
}
