//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epos.Lib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientID { get; set; }
        public string PatientNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Sex { get; set; }
        public string Occupation { get; set; }
        public string HxFrom { get; set; }
        public string ReferredFrom { get; set; }
        public string ReferredDoctor { get; set; }
        public string Allergies { get; set; }
        public string Medications { get; set; }
        public Nullable<bool> PrematureBirth { get; set; }
        public string Greeting { get; set; }
        public Nullable<System.DateTime> LastExamDate { get; set; }
    }
}
