//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epos.Lib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleID { get; set; }
        public int PatientID { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public Nullable<int> ExamID { get; set; }
        public string Status { get; set; }
        public string DoctorUserName { get; set; }
    }
}
